package com.tdtu.coreapi.invoice;

import com.tdtu.coreapi.invoice.dto.CreateInvoiceRequest;
import com.tdtu.coreapi.invoice.dto.InvoiceCreatedView;
import com.tdtu.coreapi.invoice.dto.InvoiceItemRequest;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.text.NumberFormat;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

@Service
public class InvoicePdfService {

    private static final float START_X = 48f;
    private static final float START_Y = 780f;
    private static final float LINE_HEIGHT = 18f;

    public String generate(InvoiceCreatedView invoice, CreateInvoiceRequest request) {
        try {
            Path invoiceDir = Path.of("upload", "invoices");
            Files.createDirectories(invoiceDir);

            Path pdfPath = invoiceDir.resolve(invoice.invoiceCode() + ".pdf");
            try (PDDocument document = new PDDocument()) {
                PDPage page = new PDPage(PDRectangle.A4);
                document.addPage(page);

                try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                    writeLines(contentStream, buildLines(invoice, request));
                }

                document.save(pdfPath.toFile());
            }

            return "/api/invoices/" + invoice.invoiceCode() + "/pdf";
        } catch (IOException ex) {
            throw new IllegalStateException("Unable to generate invoice PDF", ex);
        }
    }

    public Path resolve(String invoiceCode) {
        return Path.of("upload", "invoices", invoiceCode + ".pdf");
    }

    private void writeLines(PDPageContentStream contentStream, List<String> lines) throws IOException {
        float y = START_Y;
        contentStream.beginText();
        contentStream.setLeading(LINE_HEIGHT);
        contentStream.newLineAtOffset(START_X, y);
        for (int i = 0; i < lines.size(); i++) {
            if (i == 0) {
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 18);
            } else if (i == 1) {
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
            } else {
                contentStream.setFont(PDType1Font.HELVETICA, 11);
            }
            contentStream.showText(toAscii(lines.get(i)));
            contentStream.newLine();
        }
        contentStream.endText();
    }

    private List<String> buildLines(InvoiceCreatedView invoice, CreateInvoiceRequest request) {
        NumberFormat currency = NumberFormat.getNumberInstance(new Locale("vi", "VN"));
        List<String> lines = new ArrayList<>();
        lines.add("PHONE STORE INVOICE");
        lines.add("Invoice Code: " + invoice.invoiceCode());
        lines.add("Customer ID: " + invoice.customerId());
        lines.add("Customer Name: " + request.fullName());
        lines.add("Phone Number: " + request.phoneNumber());
        lines.add("Address: " + request.address());
        lines.add("Staff ID: " + request.staffId());
        lines.add("Total Quantity: " + request.quantity());
        lines.add("Total Money: " + currency.format(request.totalMoney()) + " VND");
        lines.add("Receive Money: " + currency.format(request.receiveMoney()) + " VND");
        lines.add("Money Back: " + currency.format(request.moneyBack()) + " VND");
        lines.add(" ");
        lines.add("Items:");
        for (InvoiceItemRequest item : request.items()) {
            int unitPrice = item.totalMoney() / Math.max(1, item.quantity());
            lines.add("- Product ID " + item.productId()
                    + " | Qty " + item.quantity()
                    + " | Unit " + currency.format(unitPrice)
                    + " | Total " + currency.format(item.totalMoney()));
        }
        lines.add(" ");
        lines.add("Generated by core-api PDF service.");
        return lines;
    }

    private String sanitize(String value) {
        if (value == null) {
            return "";
        }
        return value
                .replace('\n', ' ')
                .replace('\r', ' ')
                .replace('\t', ' ');
    }

    private String toAscii(String value) {
        String sanitized = sanitize(value);
        return Normalizer.normalize(sanitized, Normalizer.Form.NFD)
                .replaceAll("\\p{M}", "")
                .replaceAll("[^\\x20-\\x7E]", "?");
    }
}
